#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_systemd_action --service_name="$app" --action="stop"
yunohost service remove "$app"
ynh_remove_systemd_config
ynh_remove_nginx_config
