#!/bin/bash
source "${0%/*}/_common.sh"
source /usr/share/yunohost/helpers

yunohost service remove "$app" 2>/dev/null || true
ynh_config_remove_systemd
ynh_config_remove_nginx
ynh_config_remove_logrotate

rm -rf "/var/log/$app"
