#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_restore_file "$install_dir"
ynh_restore_file "$data_dir"
ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore_file "/etc/systemd/system/$app.service"

chown -R "$app:www-data" "$install_dir"
chown -R "$app:www-data" "$data_dir"

systemctl enable "$app" --quiet
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

ynh_systemd_action --service_name=nginx --action=reload
