#!/bin/bash
source "${0%/*}/_common.sh"
source /usr/share/yunohost/helpers

ynh_restore_file "$install_dir"
ynh_restore_file "$data_dir"
ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore_file "/etc/systemd/system/$app.service"

chown -R "$app:www-data" "$install_dir"
chown -R "$app:www-data" "$data_dir"

systemctl daemon-reload
systemctl enable "$app" --quiet
systemctl start "$app"
systemctl reload nginx
